blank_issues_enabled: false
contact_links:
  - name: OneLiteFeather Discord
    url: https://discord.onelitefeather.net
    about: If you are having issues with timings or have other minor issues, come ask us on our Discord server!
  - name: CloudNet Discord
    url: https://discord.cloudnetservice.eu/
    about: If you are having issues with CloudNet v4 or have other minor issues, come ask us on our Discord server!